# Generated by Django 3.2 on 2021-08-30 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Evote', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votestudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voteinfo',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evote.period'),
        ),
        migrations.AddField(
            model_name='listinfo',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evote.period'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='listInfo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Evote.listinfo'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
